### ISSUE TITLE
question about support tracker and deprecation

### ISSUE THREAD

**Issue by kidbrax** [pingidentity/terraform-provider-pingfederate#106]
On the [support tracker](https://github.com/pingidentity/terraform-provider-pingfederate/issues/52), there is a list of 3rd party deprecated items. Are those items that are covered in other resources or won't be covered, or just aren't needed anymore?

**Comment by wesleymccollam** [comment]
@kidbrax, these resources will be included on this provider in the future. The deprecation is just referring to the 3rd party being deprecated.

**Comment by wesleymccollam** [comment]
The title on the header is now updated to have more clarity.

**Comment by kidbrax** [comment]
Thanks for the quick response!
