### ISSUE TITLE
Request for Status and ETA on Specific Resources

### ISSUE THREAD

**Issue by F0x06** [pingidentity/terraform-provider-pingfederate#186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**New or Affected Resource(s):**

  - pf-admin-api/v1/session/authenticationSessionPolicies (GET, POST)
  - pf-admin-api/v1/session/authenticationSessionPolicies/{id} (GET, PUT, DELETE)

Greetings,

I am currently utilizing the community-developed Terraform provider for PingFederate by [iwarapter](https://github.com/iwarapter/terraform-provider-pingfederate) with some custom modifications. My objective is to transition to the official PingFederate Terraform provider for enhanced support and stability. However, I have noticed that specific resources crucial to our infrastructure setup are not listed in the [Support Tracker](https://github.com/pingidentity/terraform-provider-pingfederate/issues/52). Could you please provide an update on the status of the following resources within the official provider?

Additionally, I am interested in understanding the roadmap for the inclusion of the following resources, which are vital to our use case:

  - Authentication Selectors Resource
  - Incoming Proxy Settings Resource
  - OAuth - Access Token Mappings Resource

**Questions:**

Are there plans to include the above-mentioned resources in the official PingFederate Terraform provider?
If so, could you provide an estimated timeline or version in which these resources might become available?

Thanks,
Best regards,
Kevin V.

**Comment by wesleymccollam** [comment]
@F0x06, thank you for the issue creation! The `authenticationSessionPolicies` was missed when the Support Tracker was created and is now added to the **Deprecated 3rd Party Provider Coverage** section. All the resources requested in your issue post are now the highest priority to be worked on next. I would say you can expect most (if not all) of these resources in versions `v0.7.0` and `v0.8.0`.

**Comment by F0x06** [comment]
> @F0x06, thank you for the issue creation! The `authenticationSessionPolicies` was missed when the Support Tracker was created and is now added to the **Deprecated 3rd Party Provider Coverage** section. All the resources requested in your issue post are now the highest priority to be worked on next. You can expect most (if not all) of these resources in versions `v0.7.0` and `v0.8.0`.

Perfect! Thanks for the quick response, I'll inform you if I notice anything during the migration phase.

Best regards,
Kevin V.

**Comment by wesleymccollam** [comment]
@F0x06, I just wanted to update you on the 3 resource types below that just went out in the `v0.7.0` release of the provider.

- Authentication Selectors Resource
- Incoming Proxy Settings Resource
- OAuth - Access Token Mappings Resource
