### ISSUE TITLE
As an Identity Engineer, I would like to migrate a customer instance with integration kits

### ISSUE THREAD

**Issue by mapkon** [pingidentity/terraform-provider-pingfederate#198]
**As an** Identity Engineer,
**I want** to migrate a customer instance with integration kits
**So that** the migrated instance matches the OnPrem one and it is functional

### Context

When we designed the initial migration tool, one of the constraints for using it to migrate client deployments between instances was the lack of support for migrating Integration Kits, specifically the custom ones. The tool worked for basic configuration, but we quickly discovered that client deployments are non trivial, and almost always include an array of custom integration kits to support additional features like Open Banking. 

We thus concluded that for an migration tool to be relevant in a customer context, migrating custom integration kits was essential, since without them the 'migrated' instance wouldn't function as expected. We are pretty certain that any efforts at a migration tool that do not consider integration kits won't be as relevant in customer instances, which are often non-trivial.

### Expected Outcomes

- If there are IKs that we cannot for one reason or another migrate, the tool should validate those and flag them, potentially failing the migration until they are resolved. 
  - There should be a force option to override this default behavior
  
- After migrating an instance with integration kits
  - For successful migration, all customer integration kits should be migrated
  - The configuration for the integration kits should also be ported over. 

- Generate a report showing the migration status of integration kits:
  - If some failed to migrate, the report should flag these
    - The tool should attempt to ascertain why some of the IKs didn't migrate, and advise remedial action to the engineer
  - For those that might be inoperable, the tool should flag these too 

### Acceptance Criteria

TBD

**Comment by patrickcping** [comment]
hi @mapkon , thanks for raising!

Terraform integrations are not necessarily designed in terms of "wholistic migration tooling" but portability of Terraform HCL between different environments (especially for config promotion between development-test-production) is a core use case of Terraform.  The Terraform provider as-is assumes that the instances are deployed with the custom integration filesystem requirements in place.

We'll look into the request and spawn necessary enhancements/issues against this project, though I suspect that, to fulfil all the expected outcomes of this request (such as migration status reporting), we will need to look at a separate project initiative altogether.

If the ask is in terms of an active customer deployment, please do reach out to your account manager or customer success manager and we can discuss directly

**Comment by samir-gandhi** [comment]
Agreed with @patrickcping. Thanks again for opening, @mapkon. 

This is good feedback and is relevant to migration tooling that is separate from this Terraform project. 
We don't have an open source repository currently available for that tooling. For now, I will close this ticket and take the feedback to our internal team working on migration tooling. From there, we'll reach out to you directly regarding the status and outcomes.
