### ISSUE TITLE
Apply error for pingfederate_oauth_client

### ISSUE THREAD

**Issue by Keetika-Yogendra** [pingidentity/terraform-provider-pingfederate#203]
Hi Team,

Thank you so much for fixing the bug I mentioned yesterday. I am here to ask to fix a similar bug but, in the resource “pingfederate_oauth_client”. I am defining extended parameters like so, where I am doing a for_each on my resource: 

extended_parameters = {

param1 = {
values = [each.value.var1] 
}

param2 =  {
values = [each.value.var2] 
}

param3 = try(each.value.var3,null) == null ? {} :{
values = [each.value.var3] 
}

}

Similar to the previous issue, when the param3 is set to {} the plan and apply works but I am getting the following an error in the comparison:

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.oidcmodule.pingfederate_oauth_client.oidc_integration["test-app"], provider
│ "module.oidcmodule.provider[\"registry.terraform.io/pingidentity/pingfederate\"].pingidentity" produced an unexpected new value: .extended_parameters["param3"].values: │ was null, but now cty.SetValEmpty(cty.String).
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

I have certain instances where the variable var3 may not be defined, so that is why I have that if statement (the extended_parameter param3 only exists if var3 exists). Thank you so much in advance for your time and reactivity !

**Comment by wesleymccollam** [comment]
@Keetika-Yogendra this just went out in the latest release of the provider - [v0.8.0](https://registry.terraform.io/providers/pingidentity/pingfederate/0.8.0)
