### ISSUE TITLE
Apply Error With resource pingfederate_oauth_client 

### ISSUE THREAD

**Issue by kyogendra08** [pingidentity/terraform-provider-pingfederate#209]
Hi Team, 

Regarding the issue I had opened last week, I seem to still have the error when I set the extended_parameters to an empty value: 

RESOURCE DEFINITION : 
extended_parameters = {

param1 = {
values = ["value1"]
}

param2 = {}

}
}

ERROR: 
Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.oidcmodule.pingfederate_oauth_client.oidc_integration["test-app2"], provider
│ "module.oidcmodule.provider[\"registry.terraform.io/pingidentity/pingfederate\"].pingidentity" produced an unexpected new value: .extended_parameters: element
│ "param2" has vanished.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

I would much appreciate your assistance regarding the matter. 

Thank you so much for your reactivity !

**Comment by wesleymccollam** [comment]
@Keetika-Yogendra, we have now addressed this issue and the fix will be in the next provider release. We have now required the `values` property. This change matches the product behavior for adding extended parameters to the OAuth client - if no value is supplied, then it's not attached to the OAuth client.

**Comment by wesleymccollam** [comment]
@Keetika-Yogendra this is also now included in the [latest release](https://registry.terraform.io/providers/pingidentity/pingfederate/0.8.0) of the provider.
