### ISSUE TITLE
Apply Error with resource pingfederate_oauth_access_token_mapping

### ISSUE THREAD

**Issue by Keetika-Yogendra** [pingidentity/terraform-provider-pingfederate#210]
Hi Team, 

I am getting a similar error to my previous requests, but on the resource pingfederate_oauth_access_token_mapping. When I define the  attribute_contract_fulfillment as follows: 

  attribute_contract_fulfillment = {
       "amr" = {
           source = {
               type = "NO_MAPPING"
            }
        }, 
     "username" = {
          source = {
               type = "NO_MAPPING"
            }
        },
}

The resource does get created with the attribute_contract_fulfillment define but I am getting the following error after an apply: 

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to pingfederate_oauth_access_token_mapping.token_mappings, provider
│ "provider[\"registry.terraform.io/pingidentity/pingfederate\"].pingidentity" produced an unexpected new value:
│ .attribute_contract_fulfillment["amr"].value: was null, but now cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to pingfederate_oauth_access_token_mapping.token_mappings, provider
│ "provider[\"registry.terraform.io/pingidentity/pingfederate\"].pingidentity" produced an unexpected new value:
│ .attribute_contract_fulfillment["username"].value: was null, but now cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

Once again Thank you  for your reactivity !

**Comment by wesleymccollam** [comment]
@Keetika-Yogendra, this is also in the latest release of the provider - v0.8.0
