### ISSUE TITLE
Can you add a README

### ISSUE THREAD

**Issue by kidbrax** [pingidentity/terraform-provider-pingfederate#26]
Do you plan to add a README to let people know about the project and its status, etc? We are interested in testing with this but don't know if or when it will be stable and the plans for it.

**Comment by wesleymccollam** [comment]
@kidbrax, we have now added a README along with some other documentation to the repository. The current (and future) status of this repository is also in the README [here](https://github.com/pingidentity/terraform-provider-pingfederate#disclaimer---provider-in-development). Thank you for this issue post and let us know if you have any other questions!

**Comment by kidbrax** [comment]
Great, thanks for the quick turnaround!
