### ISSUE TITLE
Create Notification Publishers

### ISSUE THREAD

**Issue by colinhuckstep** [pingidentity/terraform-provider-pingfederate#301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**New or affected resource(s)**
Please provide a list of the new and/or affected resources/data sources, for example:
- pingfederate_notification_publisher

**Is your feature request related to a problem? Please describe.**
I'm unable to create notification publishers which are needed by other resources such as notification publishers settings

**Describe the solution you'd like**
The ability to create a notification publisher using terraform

**Describe alternatives you've considered**
API calls to create publishers.

**Potential Terraform configuration**

**References**

**Comment by wesleymccollam** [comment]
@colinhuckstep, thank you for the issue submission! The `notification_publisher` resource currently has a [Pull Request ](https://github.com/pingidentity/terraform-provider-pingfederate/pull/284), and is approved. This will be included in the provider very soon!

**Comment by colinhuckstep** [comment]
Great, thanks for the update. I'll keep an eye out for it.

**Comment by henryrecker-pingidentity** [comment]
This resource has been added in the new v0.14.0 release - https://registry.terraform.io/providers/pingidentity/pingfederate/latest
