### ISSUE TITLE
The provider pingidentity/pingfederate does not support resource type "pingfederate_kerberos_realm_settings".

### ISSUE THREAD

**Issue by colinhuckstep** [pingidentity/terraform-provider-pingfederate#302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingFederate Terraform provider Version
0.12.0

### PingFederate Version
11.3.5

### Terraform Version
Run `terraform -v` to show the version.
Terraform v1.9.3
on linux_amd64
+ provider registry.terraform.io/pingidentity/pingfederate v0.12.0

### Affected Resource(s)
Please list the resources as a list, for example:
- pingfederate_kerberos_realm_settings

### Terraform Configuration Files
```hcl
resource "pingfederate_kerberos_realm_settings" "kerberosRealmSettings" {
  debug_log_output              = false
  force_tcp                     = false
  kdc_retries                   = 3
  kdc_timeout                   = 3
  key_set_retention_period_mins = 610
}
```

### Expected Behavior
apply Kerberos Realm Settings

### Actual Behavior
```
│ Error: Invalid resource type
│
│   on kerberos_realms_settings.tf line 1, in resource "pingfederate_kerberos_realm_settings" "kerberosRealmSettings":
│    1: resource "pingfederate_kerberos_realm_settings" "kerberosRealmSettings" {
│
│ The provider pingidentity/pingfederate does not support resource type "pingfederate_kerberos_realm_settings".
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by wesleymccollam** [comment]
@colinhuckstep, thanks for submitting an issue! Currently, the only supported resource for kerberos is `kerberos_realm`. The resource you're trying to use is in the main branch, however it's not released on the registry at this time. This resource will also be on the registry very soon! The supported resources available for the provider can be found [here](https://registry.terraform.io/providers/pingidentity/pingfederate/latest/docs).

**Comment by henryrecker-pingidentity** [comment]
@colinhuckstep This resource has been added to the provider and is available on the terraform registry as of today's 0.13.0 release.
